# Generated by Django 3.1.4 on 2021-01-26 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Hidden', 'Hidden')], default='Published', max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_created', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
