# Generated by Django 3.1.4 on 2021-02-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20210201_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
