# Generated by Django 3.1.4 on 2021-02-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20210201_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Accounts.profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Accounts.profile'),
        ),
    ]
